### ISSUE TITLE
Bug: I can't open the project

### ISSUE THREAD

**Issue by win20-official** [glowsquid-launcher/glowsquid#140]
This is the error that pops out:
ERROR  workspace configuration error: package.json: no workspaces found. Turborepo requires npm workspaces to be defined in the root package.json

**Comment by win20-official** [comment]
Help me!

**Comment by win20-official** [comment]
Can you help me?

**Comment by Suya1671** [comment]
> This is the error that pops out: ERROR workspace configuration error: package.json: no workspaces found. Turborepo requires npm workspaces to be defined in the root package.json

from what I can tell you are running `npm run dev` or whatever. Glowsquid uses the `pnpm` package manager, so install it via the instructions at https://pnpm.io/installation and run `pnpm install` and then `pnpm run dev`.
